# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: cholun's blog
email: cholun@outlook.com
description: 個人部落格，一個阿肥發廢文的地方。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.cholun.me" # the base hostname & protocol for your site

encoding: utf-8

plugins: [jekyll-paginate]
paginate: 10
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown

# Sitemaps for GitHub Pages
plugins:
  - jekyll-sitemap
  - jekyll-paginate